#! /bin/sh

# startup commands

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.jpg &
$HOME/.scripts/setTouchpad &

# bspwm settings

bspc monitor -d 1 2 3 4 5

bspc config border_width        3
bspc config window_gap          8
bspc config single_monocle	true
bspc config gapless_monocle	true

bspc config normal_border_color	   "#3b4252"
bspc config focused_border_color   "#5e81ac"

bspc config split_ratio            0.52
bspc config borderless_monocle	   true
bspc config focus_follows_pointer  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
